export const activityMap = {
  pending: "Job invite was sent to",
  invited: "Added candidate,",
  "invited manual": "Added candidate,",
  "invite accepted": "Added candidate,",
  applied: "This candidate applied,",
  shortlisted: `Shortlisted this candidate,`,
  "to be screened": "Set this candidate to the status To Be Screened,",
  "to be submitted": "Set this candidate to the status To Be Submitted,",
  "awaiting review": "Set this candidate to the status Awaiting Review,",
  approved: "Approved this candidate for the job,",
  "assessment sent": "Set this candidate to the status Assessment Sent,",
  "assessment returned":
    "Set this candidate to the status Assessment Returned,",
  passed: "Set this candidate to the status Assessment passed,",
  interview_requested: "Requested an interview with",
  "to be scheduled":
    "Set this candidate to the status Interview to be Scheduled, ",
  interview_scheduled: "Scheduled an interview with",
  interview_conducted: "Conducted Interview with",
  interview_rescheduled: "Rescheduled Interview with",
  interview_rescheduled_manual: "Rescheduled Interview with",
  "to be rescheduled":
    "Set this candidate to the status Interview to be Rescheduled,",
  "invited to event": "Invited this candidate to Event,",
  "attending event": "Set this candidate to the status Attending Event,",
  "to be offered": "Set this candidate to the status To Be Offered,",
  "verbally offered": "Verbally offered the job to",
  "contract sent": "Sent a contract to",
  "verbally accepted": "Set this candidate to the status Verbally Accepted,",
  "formally accepted": "Set this candidate to the status Formally Accepted,",
  offer_requested: "Sent and offer to",
  offer_accepted: "Set this candidate to the status Offer Accepted,",
  "gathering information": "Gathering information for",
  "contract signed": "Set this candidate to the status Contract was Signed,",
  "start date confirmed": "Start date was confimed for",
  onboarding: "Set this candidate to the status Onboarding,",
  "hired applicant": "Hired",
  hired: "Hired",
  "hired manual": "Hired",
  declined: "Declined",
  declined_manual: "Declined",
  rejected: "Rejected",
  rejected_manual: "Rejected",
  cancelled: "Cancelled the application for,",
};
